#!/bin/bash
echo "=== Deploying JavaScript syntax fix to Heroku ==="
echo ""
echo "Run these commands to deploy the fix:"
echo ""
echo "1. Add the changes:"
echo "   git add ai_career_coach.html"
echo ""
echo "2. Commit the fix:"
echo "   git commit -m 'Fix JavaScript syntax error in displayResult function'"
echo ""
echo "3. Push to Heroku:"
echo "   git push heroku main"
echo ""
echo "4. Check if deployment succeeded:"
echo "   heroku logs --tail --app ai-career-coach-ronit"
echo ""
echo "The syntax error should be fixed after deployment!"
